# permissions for end users to view terraforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: terra-operator
    app.kubernetes.io/managed-by: kustomize
  name: terraform-viewer-role
rules:
- apiGroups:
  - iac.terraoperator.com
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iac.terraoperator.com
  resources:
  - terraforms/status
  verbs:
  - get
